### ISSUE TITLE
Decompose further

### ISSUE THREAD

**Issue by ecoppen** [BishalHD/Programming-challenges#2]
https://github.com/BishalHD/Programming-challenges/blob/a37412faca736b5151a50bb4f9781e8ca27ecec7/Brampton%20Manor%20Academy/Challenge_1.py#L6-L11

What if I only want one conversion in future? Currently I'm going to be given 5 results even if I only need one. This also makes it difficult to test.

Something like:
```
def rods_to_meters(rods: float):
    return rods * 5.0292
```
would be better as any mistakes can now be narrowed down to just this function, rather than somewhere in `conversions`

**Comment by BishalHD** [comment]
Thank you sir
